[package]
name = "space-invaders"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
rusty_audio = "1.2.1"
rusty_time = "0.11.3"
crossbeam = "0.8.1"
