name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path=hello/Cargo.toml --verbose
      - name: Run tests
        run: cargo test --manifest-path=hello/Cargo.toml --verbose

  buildBasics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path=basics/Cargo.toml --verbose
      - name: Run tests
        run: cargo test --manifest-path=basics/Cargo.toml --verbose